
/**
 * @file globals.h
 * @brief Contains global variables and type definitions for the Robot
 * namespace.
 */


/**
 * @namespace Robot
 * @details In order to construct the robot, the Robot namespace is used to
 * contain all of the objects that are used to control the robot. This includes
 * the subsystems, methods, and global objects. We use PROS extensively for the
 * robot, it can be found at <A HREF="https://pros.cs.purdue.edu">PROS</A>
 * @authors Mori Meldovia
 * @brief Contains all objects generated by the 6546C team - Contains all of the
 * subsystems, methods, and global objects.
 */
